### ISSUE TITLE
Filter out files with wildcards/extensions

### ISSUE THREAD

**Issue by Tasin5541** [fw10/veracode-javascript-packager#6]
Our test files are kept alongside the components and not in a separate folder. We have some other files as well (including env files) that we would like to filter out. Is there a flag that we can use to filter out certain files with wildcards/extensions?

**Comment by dub-flow** [comment]
Hi there, at the moment, a flag like this does not exist.

But as long as your test files have typical test extensions, such as ‘.spec.js’, they would be automatically filtered out. What extensions do your test files have?

What other files would you want to be excluded from the output zip?

**Comment by Tasin5541** [comment]
Our test files use `spec.tsx` extension. These are not getting ignored in the zip.

Other files I would like to exclude are .local, . production extensions. And also some config files for cypress.

**Comment by dub-flow** [comment]
Ah yes '.spec.tsx' is currently not ignored. I will add them to the list of extensions to be excluded. I'm currently on PTO so likely won't be able to do this until early November. I will keep you posted.

Will also think of a way to exclude the other files. Either just ignoring some more extensions manually or maybe a new flag like you suggested.

Thanks for raising this issue!

**Comment by dub-flow** [comment]
Thanks for creating the Merge Request! 😊

Will create a new release soon for you that will include this change. 

Regarding a new flag: Since this is not an official Veracode project (just something that I, as a Veracode employee, maintain) I don't see myself having time for any change that requires more time and proper testing in the near future. Would it work for you to create new MRs if you want more files and extensions to be excluded?

Note that in the future we aim to include this functionality in the Veracode CLI which means that it would be officially supported by Veracode (which would make changing things much easier)!
